import { environment } from 'src/environments/environment';

export default class ImagesConstants {
    
    static readonly HOUSE_IMAGES = {
        SALA_SANTA_AMELIA_1: environment.baseUrl + '/images/House/1-SALA-SANTA-AMELIA.jpg',
        MORAR_MAIS_2: environment.baseUrl + '/images/House/2-MORAR-MAIS.jpg',
        SALAS_SAVASSI_3: environment.baseUrl + '/images/House/3-SALAS-SAVASSI.jpg',
        SALAS_BURITIS_4: environment.baseUrl + '/images/House/4-SALAS-BURITIS.jpg',
        COZINHA_SION_5: environment.baseUrl + '/images/House/5-COZINHA-SION.jpg',
        MOBILE: {
            MOB_SALA_SANTA_AMELIA_1: environment.baseUrl + '/images/House/Mobile/1-MOB-SALA-SANTA-AMELIA.jpg',
            MOB_MORAR_MAIS_2: environment.baseUrl + '/images/House/Mobile/2-MOB-MORAR-MAIS.jpg',
            MOB_SALAS_SAVASSI_3: environment.baseUrl + '/images/House/Mobile/3-MOB-SALAS-SAVASSI.jpg',
            MOB_SALA_BURITIS_4: environment.baseUrl + '/images/House/Mobile/4-MOB-SALA-BURITIS.jpg',
            MOB_COZINHA_SION_5: environment.baseUrl + '/images/House/Mobile/5-MOB-COZINHA-SION.jpg'
        },
        PROJECTS: {
            SANTO_AGOSTINHO_1: environment.baseUrl + '/images/House/Projects/01-SANTO-AGOSTINHO.jpg',
            ANCHIETA_2: environment.baseUrl + '/images/House/Projects/02-ANCHIETA.jpg',
            BURITIS_3: environment.baseUrl + '/images/House/Projects/03-BURITIS.jpg',
            HOME_OFFICE_4: environment.baseUrl + '/images/House/Projects/04-HOME-OFFICE.jpg',
            SANTA_AMELIA_5: environment.baseUrl + '/images/House/Projects/05-SANTA-AMELIA.jpg',
            FUNCIONARIOS_6: environment.baseUrl + '/images/House/Projects/06-FUNCIONARIOS.jpg',
            SUITE_CASA_7: environment.baseUrl + '/images/House/Projects/07-SUITE-CASA.jpg',
            SAVASSI_8: environment.baseUrl + '/images/House/Projects/08-SAVASSI.jpg',
            AREA_GOUMET_9: environment.baseUrl + '/images/House/Projects/09-AREA-GOURMET-SA.jpg',
            PADRE_EUSTAQUIO_10: environment.baseUrl + '/images/House/Projects/10-PADRE-EUSTAQUIO.jpg',
            BELVEDERE_11: environment.baseUrl + '/images/House/Projects/11-BELVEDERE.jpg',
            MORAR_MAIS_12: environment.baseUrl + '/images/House/Projects/12-MORAR-MAIS.jpg',
            COZINHA_SION_13: environment.baseUrl + '/images/House/Projects/13-COZINHA-SION.jpg',
            CONTAGEM_14: environment.baseUrl + '/images/House/Projects/14-CONTAGEM.jpg',
            LAGOA_SANTA_15: environment.baseUrl + '/images/House/Projects/15-LAGOA-SANTA.jpg',
            PLANALTO_16: environment.baseUrl + '/images/House/Projects/16-PLANALTO.jpg',
            QUARTO_HOME_OFF_SION_17: environment.baseUrl + '/images/House/Projects/17-QUARTO-HOME-OFF-SION.jpg',
            QUARTO_BEBE_CAICARA_18: environment.baseUrl + '/images/House/Projects/18-QUARTO-BEBE-CAICARA.jpg',
            RESID_VARGINHA_19: environment.baseUrl + '/images/House/Projects/19-RESID-VARGINHA.jpg',
        },
        SPECIFICS: {
            RESIDENCIA_SANTO_AGOSTINHO: {
                SALA: environment.baseUrl + '/images/House/Projects/1-RESIDENCIA-SANTO-AGOSTINHO/1-sala-sto-ag.jpg',
                COZINHA: environment.baseUrl + '/images/House/Projects/1-RESIDENCIA-SANTO-AGOSTINHO/2-cozinha-sto-ag.jpg',
                COZINHA_2: environment.baseUrl + '/images/House/Projects/1-RESIDENCIA-SANTO-AGOSTINHO/4-cozinha-sto-ag.jpg',
                COZINHA_3: environment.baseUrl + '/images/House/Projects/1-RESIDENCIA-SANTO-AGOSTINHO/5-cozinha-sto-ag.jpg',
            },
            RESIDENCIA_ANCHIETA: {
                INFANTIL: environment.baseUrl + '/images/House/Projects/2-RESIDENCIA-ANCHIETA/1-sala-belvedere.jpg',
                INFANTIL_2: environment.baseUrl + '/images/House/Projects/2-RESIDENCIA-ANCHIETA/2-sala-belvedere.jpg',
                CASAL: environment.baseUrl + '/images/House/Projects/2-RESIDENCIA-ANCHIETA/3-casal-anchieta.jpg',
                BANHEIRO: environment.baseUrl + '/images/House/Projects/2-RESIDENCIA-ANCHIETA/4-banheiro-anchieta.jpg',
            },
            RESIDENCIA_BURITIS: {
                SALA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/3-casal-anchieta.jpg',
                COZINHA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/4-banheiro-anchieta.jpg',
                COZINHA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                CASAL: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                CASAL_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/3-casal-anchieta.jpg',
                SOLTEIRO: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/4-banheiro-anchieta.jpg',
                SOLTEIRO_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/4-banheiro-anchieta.jpg',
            },
            HOME_OFFICE_SAVASSI: {
                HOME_OFFICE: environment.baseUrl + '/images/House/Projects/4-HOME-OFFICE-SAVASSI/1-home-office-savassi.jpg',
                HOME_OFFICE_2: environment.baseUrl + '/images/House/Projects/4-HOME-OFFICE-SAVASSI/2-home-office-savassi.jpg',
            },
            RESIDENCIA_SANTA_AMELIA: {
                SALA: environment.baseUrl + '/images/House/Projects/5-RESIDENCIA-SANTA-AMELIA/1-sala-santa-amelia.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/5-RESIDENCIA-SANTA-AMELIA/2-sala-santa-amelia.jpg',
                SALA_3: environment.baseUrl + '/images/House/Projects/5-RESIDENCIA-SANTA-AMELIA/3-sala-santa-amelia.jpg',
                CASAL: environment.baseUrl + '/images/House/Projects/5-RESIDENCIA-SANTA-AMELIA/4-casal-santa-amelia.jpg',
                CASAL_2: environment.baseUrl + '/images/House/Projects/5-RESIDENCIA-SANTA-AMELIA/5-casal-santa-amelia.jpg',
                HOME_OFFICE: environment.baseUrl + '/images/House/Projects/5-RESIDENCIA-SANTA-AMELIA/6-home-office-santa-amelia.jpg',
                HOME_OFFICE_2: environment.baseUrl + '/images/House/Projects/5-RESIDENCIA-SANTA-AMELIA/7-home-office-santa-amelia.jpg',
            },
            RESIDENCIA_FUNCIONARIOS: {
                SALA_FUNCIONARIOS: environment.baseUrl + '/images/House/Projects/6-RESIDENCIA-FUNCIONARIOS/1-sala-funcionarios.jpg',
                SALA_FUNCIONARIOS_2: environment.baseUrl + '/images/House/Projects/6-RESIDENCIA-FUNCIONARIOS/2-sala-funcionarios.jpg',
                QUARTO_FUNCIONARIOS: environment.baseUrl + '/images/House/Projects/6-RESIDENCIA-FUNCIONARIOS/3-quarto-funcionarios.jpg',
                LAVABO_FUNCIONARIOS: environment.baseUrl + '/images/House/Projects/6-RESIDENCIA-FUNCIONARIOS/4-lavabo-funcionarios.jpg',
            },
            SUITE_OURO_PRETO: {
                SOLTEIRA_OURO_PRETO: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/1-solteira-ouro-preto.jpg',
                SOLTEIRA_OURO_PRETO_2: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/2-solteira-ouro-preto.jpg',
                BANHEIRO_OURO_PRETO: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/3-banheiro-ouro-preto.jpg',
            },
            RESIDENCIA: {
                SALA: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/1-sala-savassi.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/2-sala-savassi.jpg',
                SALA_3: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/3-sala-savassi.jpg',
                BANEIRO: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/4-banheiro-savassi.jpg',
                INFANTIL: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/4-infantil-savassi.jpg',
                BANEIRO_2: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/5-banheiro-savassi.jpg',
                HOME_OFFICE_VERMELHO: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/5-home-office-vermelho-savassi.jpg',
                INFANTIL_2: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/6-infantil-savassi.jpg',
                CASAL: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/7-casal-savassi.jpg',
                CASAL_2: environment.baseUrl + '/images/House/Projects/8-RESIDENCIA-SAVASSI/8-casal-savassi.jpg',
            },
            AREA_GOURMET_SANTA_AMELIA: {
                AREA_GOURMET: environment.baseUrl + '/images/House/Projects/9-AREA-GOURMET- SANTA-AMELIA/1-area-gourmet-santa-amelia.jpg',
                AREA_GOURMET_2: environment.baseUrl + '/images/House/Projects/9-AREA-GOURMET- SANTA-AMELIA/2-area-gourmet-santa-amelia.jpg',
                AREA_GOURMET_3: environment.baseUrl + '/images/House/Projects/9-AREA-GOURMET- SANTA-AMELIA/3-area-gourmet-santa-amelia.jpg',
            },
            RESIDENCIA_PADRE_EUSTAQUIO: {
                SALA: environment.baseUrl + '/images/House/Projects/10-RESIDENCIA-PADRE-EUSTAQUIO/1-sala-solange-padre-eustaquio.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/10-RESIDENCIA-PADRE-EUSTAQUIO/2-sala-solange-padre-eustaquio.jpg',
                COZINHA: environment.baseUrl + '/images/House/Projects/10-RESIDENCIA-PADRE-EUSTAQUIO/3-cozinha-solange-padre-eustaquio.jpg',
                COZINHA_2: environment.baseUrl + '/images/House/Projects/10-RESIDENCIA-PADRE-EUSTAQUIO/4-cozinha-solange-padre-eustaquio.jpg',
                BANHEIRO: environment.baseUrl + '/images/House/Projects/10-RESIDENCIA-PADRE-EUSTAQUIO/5-banheiro-solange-padre-eustaquio.jpg',
            },
            SALAS_CONJUGADAS_BELVEDERE: {
                SALA: environment.baseUrl + '/images/House/Projects/11-SALAS-CONJUGADAS-BELVEDERE/1-sala-belvedere.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/11-SALAS-CONJUGADAS-BELVEDERE/2-sala-belvedere.jpg',
                SALA_3: environment.baseUrl + '/images/House/Projects/11-SALAS-CONJUGADAS-BELVEDERE/2-sala-belvedere.jpg',
            },
            PREMIO_MORAR_MAIS: {
                MORAR_MAIS: environment.baseUrl + '/images/House/Projects/12-PREMIO-MORAR-MAIS-2018/1-morar-mais.jpg',
                MORAR_MAIS_2: environment.baseUrl + '/images/House/Projects/12-PREMIO-MORAR-MAIS-2018/2-morar-mais.jpg',
                MORAR_MAIS_3: environment.baseUrl + '/images/House/Projects/12-PREMIO-MORAR-MAIS-2018/3-morar-mais.jpg',
                MORAR_MAIS_4: environment.baseUrl + '/images/House/Projects/12-PREMIO-MORAR-MAIS-2018/4-morar-mais.jpg',
                MORAR_MAIS_5: environment.baseUrl + '/images/House/Projects/12-PREMIO-MORAR-MAIS-2018/5-morar-mais.jpg',
                MORAR_MAIS_6: environment.baseUrl + '/images/House/Projects/12-PREMIO-MORAR-MAIS-2018/6-morar-mais.jpg',
                MORAR_MAIS_7: environment.baseUrl + '/images/House/Projects/12-PREMIO-MORAR-MAIS-2018/7-morar-mais.jpg',
                MORAR_MAIS_8: environment.baseUrl + '/images/House/Projects/12-PREMIO-MORAR-MAIS-2018/8-morar-mais.jpg',
                MORAR_MAIS_9: environment.baseUrl + '/images/House/Projects/12-PREMIO-MORAR-MAIS-2018/9-morar-mais.jpg',
                MORAR_MAIS_10: environment.baseUrl + '/images/House/Projects/12-PREMIO-MORAR-MAIS-2018/10-morar-mais.jpg',
                MORAR_MAIS_11: environment.baseUrl + '/images/House/Projects/12-PREMIO-MORAR-MAIS-2018/11-morar-mais.jpg',
            },
            COZINHA_SION: {
                COZINHA: environment.baseUrl + '/images/House/Projects/13-COZINHA-SION/1-cozinha-sion.jpg',
                COZINHA_2: environment.baseUrl + '/images/House/Projects/13-COZINHA-SION/2-cozinha-sion.jpg',
                COZINHA_3: environment.baseUrl + '/images/House/Projects/13-COZINHA-SION/3-cozinha-sion.jpg',
                COZINHA_4: environment.baseUrl + '/images/House/Projects/13-COZINHA-SION/4-cozinha-sion.jpg',
                COZINHA_5: environment.baseUrl + '/images/House/Projects/13-COZINHA-SION/5-cozinha-sion.jpg',
                COZINHA_6: environment.baseUrl + '/images/House/Projects/13-COZINHA-SION/6-cozinha-sion.jpg',
            },
            RESIDENCIA_CONTAGEM: {
                SALA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                CASAL_1: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/3-sala-belvedere.jpg',
                CASAL_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/4-sala-belvedere.jpg',
                CASAL_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/5-sala-belvedere.jpg',
                CASAL_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/6-sala-belvedere.jpg',
            },
            RESIDENCIA_LAGOA_SANTA: {
                SALA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_4: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_5: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                COZINHA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                COZINHA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                COZINHA_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                CASAL_1: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                CASAL_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                CASAL_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                BANHEIRO_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
            },
            RESIDENCIA_PLANALTO: {
                SALA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_4: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_5: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
            },
            QUARTO_HOME_OFFICE_SION: {
                QUARTO: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                QUARTO_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                QUARTO_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                HOME_OFFICE: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                HOME_OFFICE_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
            },
            QUARTO_BEBE_CAICARA: {
                INFANTIL_CAICARA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                INFANTIL_CAICARA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                INFANTIL_CAICARA_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
            },
            RESIDENCIA_VARGINHA: {
                ESTAR: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                COZINHA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                COZINHA_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                CASAL: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                CASAL_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                CASAL_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                BANHEIRO: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                BANHEIRO_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
            },
            SALA_COZINHA_PADRE_EUSTAQUIO: {
                SALA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                COZINHA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                COZINHA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
            },
            SALA_COZINHA_PADRE_EUSTAQUIO_2: {
                SALA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_4: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_5: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_6: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
            },
            ANDAR_CASA_SANTA_AMELIA: {
                SALA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_4: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_5: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                COZINHA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                COZINHA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                CASAL: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                CASAL_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                CASAL_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                INFANTIL: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                INFANTIL_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                INFANTIL_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                INFANTIL_4: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                HOME_OFFICE: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                HOME_OFFICE_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                HOME_OFFICE_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
            },
            RESIDENCIA_GUTIERREZ: {
                SALA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_4: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SALA_5: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_6: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SALA_7: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                COZINHA: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                COZINHA_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                COZINHA_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                BANHEIRO: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                BANHEIRO_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                BANHEIRO_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SOLTEIRO: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                SOLTEIRO_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                SOLTEIRO_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                INFANTIL: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/1-sala-belvedere.jpg',
                INFANTIL_2: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                INFANTIL_3: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
                INFANTIL_4: environment.baseUrl + '/images/House/Projects/3-RESIDENCIA-BURITIS/2-sala-belvedere.jpg',
            },
        }
    }

    static readonly SHARED_IMAGES = {
        MARINA: environment.baseUrl + '/images/MARINA.jpg',
        AMANDA: environment.baseUrl + '/images/AMANDA.jpg',
    }
}